---
title: "p8105_hw2_wz2630"
output: github_document
date: "2023-09-28"
---
```{r}
library(tidyverse)
library(readxl)
```

# Problem 1
```{r}
pols_month_df = 
  read_csv("hw2_datasets/pols-month.csv") |> 
  mutate(year = year(mon), month = month(mon), day = day(mon),
         
         case_match(
          month,
          1 ~ "January",
          2 ~ "February",
          3 ~ "March",
          4 ~ "April",
          5 ~ "May",
          6 ~ "June",
          7 ~ "July",
          8 ~ "August",
          9 ~ "September",
          10 ~ "October",
          11 ~ "November",
          12 ~ "December"),
         
         president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop"))
    
  
```



```{r}
#snp_df = 
  #read_csv("hw2_datasets/snp.csv") |> 
  #mutate(month = month(date), day = day(date), year = year(date),
         #case_match(
         # month,
          #1 ~ "January",
          #2 ~ "February",
          #3 ~ "March",
          #4 ~ "April",
          #5 ~ "May",
          #6 ~ "June",
          #7 ~ "July",
          #8 ~ "August",
         # 9 ~ "September",
         # 10 ~ "October",
        #  11 ~ "November",
        #  12 ~ "December"))
```


# Problem 2
```{r}
# Mr. Trash Wheel sheet
mr_trash_wheel = 
  readxl::read_excel("hw2_datasets/202207 Trash Wheel Collection Data.xlsx", 
                     range = "A2:N549") |> 
  janitor::clean_names() |> 
  mutate(homes_powered_new = (weight_tons*500)/30, 
         trash_wheel = "mr",
         year = as.numeric(year))
```

```{r}
# Professor Trash Wheel
prof_trash_wheel = 
  readxl::read_excel("hw2_datasets/202207 Trash Wheel Collection Data.xlsx", 
                     sheet = 2, 
                     range = "A2:M96") |> 
  janitor::clean_names() |> 
  mutate(homes_powered_new = (weight_tons*500)/30, 
         trash_wheel = "professor")
  # ???
  year = factor(c(2014:2022))
  year = as.numeric(as.character(year))
  year = is.numeric(year)
```

```{r}
# Gwynnda
gwynnda_trash_wheel = 
  readxl::read_excel("hw2_datasets/202207 Trash Wheel Collection Data.xlsx", 
                     sheet = 4, 
                     range = "A2:K108") |> 
  janitor::clean_names() |> 
  mutate(homes_powered_new = (weight_tons*500)/30, 
         trash_wheel = "gwynnda")
```

```{r}
# combining 3 trashwheel datasets
trash_wheels_df =
  bind_rows(mr_trash_wheel, prof_trash_wheel, gwynnda_trash_wheel)
```
The combined dataset has 747 observations and 17 variables.

# Problem 3
```{r}
# load baseline demographics data
mci_baseline = 
  read_csv("hw2_datasets/data_mci/MCI_baseline.csv",
           skip = 1) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(sex, 1 ~ "male",0 ~ "female"),
    apoe4 = case_match(apoe4, 1 ~ "carrier", 0 ~ "non-carrier")) |> 
  rename("study_id" = "id")
  
  
```

```{r}
# load amyloid data
mci_amyloid = 
  read_csv("hw2_datasets/data_mci/mci_amyloid.csv",
           skip = 1) |> 
  janitor::clean_names()
```

```{r}
# Check whether some participants appear in only the baseline or amyloid datasets

```


```{r}
# combine baseline and amyloid datasets
baseline_amyloid = 
  left_join(mci_baseline, mci_amyloid, by = "study_id") |> 
  filter(!is.na(baseline)) # removes na under baseline variable
  
```












