p8105_hw2_wz2630
================
2023-09-28

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

# Problem 1

``` r
pols_month_df = 
  read_csv("hw2_datasets/pols-month.csv") |> 
  mutate(year = year(mon), month = month(mon), day = day(mon),
         
         case_match(
          month,
          1 ~ "January",
          2 ~ "February",
          3 ~ "March",
          4 ~ "April",
          5 ~ "May",
          6 ~ "June",
          7 ~ "July",
          8 ~ "August",
          9 ~ "September",
          10 ~ "October",
          11 ~ "November",
          12 ~ "December"),
         
         president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop"))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#snp_df = 
  #read_csv("hw2_datasets/snp.csv") |> 
  #mutate(month = month(date), day = day(date), year = year(date),
         #case_match(
         # month,
          #1 ~ "January",
          #2 ~ "February",
          #3 ~ "March",
          #4 ~ "April",
          #5 ~ "May",
          #6 ~ "June",
          #7 ~ "July",
          #8 ~ "August",
         # 9 ~ "September",
         # 10 ~ "October",
        #  11 ~ "November",
        #  12 ~ "December"))
```

# Problem 2

Mr. Trash Wheel

``` r
mr_trash_wheel = 
  readxl::read_excel("hw2_datasets/202309 Trash Wheel Collection Data.xlsx", 
                     range = "A2:N586") |> 
  janitor::clean_names() |> 
  mutate(homes_powered = (weight_tons*500)/30, 
         trash_wheel = "mr",
         year = as.numeric(year))
```

Professor Trash Wheel

``` r
prof_trash_wheel = 
  readxl::read_excel("hw2_datasets/202309 Trash Wheel Collection Data.xlsx", 
                     sheet = 2, 
                     range = "A2:M108") |> 
  janitor::clean_names() |> 
  mutate(homes_powered = (weight_tons*500)/30, 
         trash_wheel = "professor")
```

Gwynnda Trash Wheel

``` r
gwynnda_trash_wheel = 
  readxl::read_excel("hw2_datasets/202309 Trash Wheel Collection Data.xlsx", 
                     sheet = 4, 
                     range = "A2:L157") |> 
  janitor::clean_names() |> 
  mutate(homes_powered = (weight_tons*500)/30, 
         trash_wheel = "gwynnda")
```

Combining 3 trashwheel datasets

``` r
trash_wheels_df =
  bind_rows(mr_trash_wheel, prof_trash_wheel, gwynnda_trash_wheel)

# total weight of trash collected by Professor Trash Wheel
sum(prof_trash_wheel[, 'weight_tons'])
```

    ## [1] 216.26

``` r
# total number of cigarette butts collected by Gwynnda in July of 2021
gwynnda_trash_wheel |> 
    group_by(year) |>  
    summarize(num = n(),
              cig_butts_total = sum(cigarette_butts))
```

    ## # A tibble: 3 × 3
    ##    year   num cig_butts_total
    ##   <dbl> <int>           <dbl>
    ## 1  2021    49           98300
    ## 2  2022    85          205410
    ## 3  2023    21           63300

The combined dataset has 747 observations and 17 variables. The total
weight of trash collected by Professor Trash Wheel is 216.26 tons. The
total number of cigarette butts collected by Gwynnda in July of 2021 is
98,300.

# Problem 3

``` r
# Load, clean, and filter baseline demographics data
mci_baseline = 
  read_csv("hw2_datasets/data_mci/MCI_baseline.csv",
           skip = 1,
           na = c(".")) |> 
  janitor::clean_names() |> 
  rename("study_id" = "id") |> 
  mutate(
    sex = case_match(
      sex, 
      1 ~ "male",
      0 ~ "female"),
    apoe4 = case_match(
      apoe4, 
      1 ~ "carrier", 
      0 ~ "non-carrier")) |> 
  filter(age_at_onset - current_age > 0) #exclusion criteria: mci at baseline
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# average baseline age
mci_baseline |> 
    summarize(num = n(),
              mean = mean(current_age))
```

    ## # A tibble: 1 × 2
    ##     num  mean
    ##   <int> <dbl>
    ## 1    93  65.5

``` r
# are we looking for mean age of filtered data? yes


# proportion of women in the study are APOE4 carriers
nrow(filter(mci_baseline, sex == "female" & apoe4 == "carrier")) / nrow(filter(mci_baseline, sex == "female"))
```

    ## [1] 0.6666667

**Important steps to import process:** The important steps to importing
the dataset include using the read_csv function, cleaning the variable
names into snake case, using the case_match function to turn numeric
values of sex and apoe4 into descriptive characters, and removing
participants who do not fulfill baseline requirements.

**Relevant features of dataset:** ??? dimensions, variables present,
anti_joins, come up with explanations, guesswork

There were originally 483 participants recruited and we then removed
those who did not meet the inclusion criteria of no MCI at baseline and
filtering for those who do develop MCI, we get 93 remaining
participants. The average baseline age is **65.5** years old. **66.67%**
of women in the study are APOE4 carriers.

``` r
# Load amyloid data
mci_amyloid = 
  read_csv("hw2_datasets/data_mci/mci_amyloid.csv",
           skip = 1) |> 
  janitor::clean_names()
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Check whether some participants appear in only the baseline or amyloid
datasets

``` r
# # shows observations that are only in mci_baseline dataset
anti_join(mci_baseline, mci_amyloid, by="study_id")
```

    ## # A tibble: 3 × 6
    ##   study_id current_age sex    education apoe4       age_at_onset
    ##      <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1       14        58.4 female        20 non-carrier         66.2
    ## 2       49        64.7 male          16 non-carrier         68.4
    ## 3      268        61.4 female        18 carrier             67.5

There are 8 participants that are only included in baseline, but not the
amyloid dataset. The study_id of these participants include: 14, 49, 92,
179, 268, 304, 389, 412.

``` r
# shows observations that are only in mci_amyloid dataset
anti_join(mci_amyloid, mci_baseline, by="study_id")
```

    ## # A tibble: 397 × 6
    ##    study_id baseline    time_2      time_4      time_6      time_8     
    ##       <dbl> <chr>       <chr>       <chr>       <chr>       <chr>      
    ##  1        1 0.1105487   <NA>        0.109325197 0.104756131 0.107257697
    ##  2        2 0.107481183 0.109157373 0.109457839 0.105729713 0.10661845 
    ##  3        4 0.109251358 0.108699686 0.110540386 0.107476797 0.111212209
    ##  4        6 0.112426974 0.112853415 0.11143945  0.110279277 0.114982747
    ##  5        8 0.109563372 0.109470828 <NA>        0.108742168 0.110268552
    ##  6        9 0.112101884 0.109781199 0.108832888 <NA>        <NA>       
    ##  7       10 0.1116094   0.111592149 <NA>        <NA>        0.110051296
    ##  8       11 0.109119335 0.109316496 0.1114037   0.108586573 0.108993335
    ##  9       12 0.112042298 0.114167481 0.109859682 0.106842794 0.107334106
    ## 10       15 0.111544948 <NA>        0.110798711 0.110378192 0.106742725
    ## # ℹ 387 more rows

There are 12 participants that are only included in amyloid, but not the
baseline dataset.The study_id of these participants include: 484, 485,
486, 487, 488, 489, 490, 491, 492, 493, 494, 495.

``` r
# shows observations that are only in mci_amyloid dataset
mci = 
  inner_join(mci_baseline, mci_amyloid, by = "study_id")
```

After combining the demographic and biomarker datasets so that only
participants who appear in both datasets are retained, the resulting
dataset (baseline_amyloid) consists of **475** observations with 11
variables.

``` r
#Export the result as a CSV to your data directory
write_csv(mci, "./mci_df_cleaned.csv")
```
